import { ExcursionType } from "./types";

export const excursions: ExcursionType[] = [
  {
    image: "/images/excursion1.png",
    rating: 4.5,
    ratingCount: 72,
    isIndividual: true,
    name: "Открытие древнего Бухары",
    from: "bukhara",
    languages: "english, russian, chinese",
    price: 480,
    forPerson: false,
    priceWithoutDiscount: 530,
    id: 1,
  },
  {
    image: "/images/excursion2.png",
    rating: 4.2,
    ratingCount: 37,
    isIndividual: false,
    name: "Экспедиция в горы Нуратау",
    from: "navoi",
    languages: "english, russian, chinese",
    price: 320,
    forPerson: true,
    priceWithoutDiscount: 400,
    id: 2,
  },
  {
    image: "/images/excursion3.png",
    rating: 3.9,
    ratingCount: 55,
    isIndividual: true,
    name: "Тур в Чарвак и Чимган",
    from: "tashkent",
    languages: "english, russian, chinese",
    price: 290,
    forPerson: true,
    priceWithoutDiscount: 360,
    id: 3,
  },
  {
    image: "/images/excursion4.png",
    rating: 4.0,
    ratingCount: 61,
    isIndividual: true,
    name: "Хива — город-сказка",
    from: "urgench",
    languages: "english, russian, chinese",
    price: 410,
    forPerson: false,
    priceWithoutDiscount: 490,
    id: 4,
  },
  {
    image: "/images/excursion5.png",
    rating: 4.7,
    ratingCount: 29,
    isIndividual: true,
    name: "Узбекская кухня и мастер-класс",
    from: "samarkand",
    languages: "english, russian, chinese",
    price: 180,
    forPerson: true,
    priceWithoutDiscount: 250,
    id: 5,
  },
  {
    image: "/images/excursion6.png",
    rating: 4.3,
    ratingCount: 88,
    isIndividual: true,
    name: "По следам Великого шелкового пути",
    from: "andijan",
    languages: "english, russian, chinese",
    price: 520,
    forPerson: true,
    priceWithoutDiscount: 620,
    id: 6,
  },
  {
    image: "/images/excursion7.png",
    rating: 4.6,
    ratingCount: 67,
    isIndividual: true,
    name: "Мистическая ночь в пустыне",
    from: "nukus",
    languages: "english, russian, chinese",
    price: 300,
    forPerson: false,
    priceWithoutDiscount: 370,
    id: 7,
  },
  {
    image: "/images/excursion8.png",
    rating: 4.0,
    ratingCount: 33,
    isIndividual: true,
    name: "Фототур по Самарканду",
    from: "samarkand",
    languages: "english, russian, chinese",
    price: 250,
    forPerson: true,
    priceWithoutDiscount: 320,
    id: 8,
  },
  {
    image: "/images/excursion9.png",
    rating: 4.8,
    ratingCount: 90,
    isIndividual: true,
    name: "Поход в Кызылкумы",
    from: "navoi",
    languages: "english, russian, chinese",
    price: 410,
    forPerson: true,
    priceWithoutDiscount: 500,
    id: 9,
  },
  {
    image: "/images/excursion10.png",
    rating: 3.7,
    ratingCount: 45,
    isIndividual: true,
    name: "Традиции и ремесла Коканда",
    from: "fergana",
    languages: "english, russian, chinese",
    price: 310,
    forPerson: false,
    priceWithoutDiscount: 380,
    id: 10,
  },
  {
    image: "/images/excursion11.png",
    rating: 4.4,
    ratingCount: 62,
    isIndividual: true,
    name: "Религиозные памятники Ташкента",
    from: "tashkent",
    languages: "english, russian, chinese",
    price: 290,
    forPerson: true,
    priceWithoutDiscount: 360,
    id: 11,
  },
  {
    image: "/images/excursion12.png",
    rating: 4.1,
    ratingCount: 51,
    isIndividual: true,
    name: "Жемчужины Каракалпакии",
    from: "nukus",
    languages: "english, russian, chinese",
    price: 440,
    forPerson: false,
    priceWithoutDiscount: 500,
    id: 12,
  },
  {
    image: "/images/excursion13.png",
    rating: 4.0,
    ratingCount: 39,
    isIndividual: true,
    name: "Культурное погружение в Ташкент",
    from: "tashkent",
    languages: "english, russian, chinese",
    price: 350,
    forPerson: true,
    priceWithoutDiscount: 420,
    id: 13,
  },
  {
    image: "/images/excursion14.png",
    rating: 3.9,
    ratingCount: 27,
    isIndividual: true,
    name: "Загадки пустыни и караван-сараи",
    from: "bukhara",
    languages: "english, russian, chinese",
    price: 370,
    forPerson: false,
    priceWithoutDiscount: 450,
    id: 14,
  },
  {
    image: "/images/excursion15.png",
    rating: 4.2,
    ratingCount: 34,
    isIndividual: true,
    name: "Тайны древней Хорезмской цивилизации",
    from: "urgench",
    languages: "english, russian, chinese",
    price: 390,
    forPerson: true,
    priceWithoutDiscount: 460,
    id: 15,
  },
  {
    image: "/images/excursion16.png",
    rating: 4.5,
    ratingCount: 69,
    isIndividual: true,
    name: "Тур на озеро Айдаркуль",
    from: "navoi",
    languages: "english, russian, chinese",
    price: 280,
    forPerson: false,
    priceWithoutDiscount: 350,
    id: 16,
  },
  {
    image: "/images/excursion17.png",
    rating: 4.0,
    ratingCount: 58,
    isIndividual: true,
    name: "Архитектурные шедевры Самарканда",
    from: "samarkand",
    languages: "english, russian, chinese",
    price: 330,
    forPerson: true,
    priceWithoutDiscount: 400,
    id: 17,
  },
];

export const cities = ["Ташкент", "Самарканд", "Бухара", "Хива"];
