import { ExcursionType } from "./types";

export const excursions: ExcursionType[] = [
  {
    image: "/images/excursion1.png",
    rating: 4.1,
    ratingCount: 43,
    isIndividual: true,
    name: "Путешествие по Самарканду и Ташкенту, Чимгану, Хиве, Янгиабад",
    from: "tashkent",
    languages: "english, russian, chinese",
    price: 600,
    forPerson: true,
    priceWithoutDiscount: 710,
  },
  {
    image: "/images/excursion2.png",
    rating: 4.1,
    ratingCount: 43,
    isIndividual: false,
    name: "Путешествие по Самарканду",
    from: "tashkent",
    languages: "english, russian, chinese",
    price: 600,
    forPerson: true,
    priceWithoutDiscount: 710,
  },
  {
    image: "/images/excursion3.png",
    rating: 4.1,
    ratingCount: 43,
    isIndividual: true,
    name: "Путешествие по Самарканду и Ташкенту, Чимгану, Хиве, Янгиабад",
    from: "tashkent",
    languages: "english, russian, chinese",
    price: 600,
    forPerson: true,
    priceWithoutDiscount: 710,
  },
  {
    image: "/images/excursion4.png",
    rating: 4.1,
    ratingCount: 43,
    isIndividual: true,
    name: "Путешествие по Самарканду и Ташкенту, Чимгану, Хиве, Янгиабад",
    from: "tashkent",
    languages: "english, russian, chinese",
    price: 600,
    forPerson: true,
    priceWithoutDiscount: 710,
  },
  {
    image: "/images/excursion5.png",
    rating: 4.1,
    ratingCount: 43,
    isIndividual: true,
    name: "Путешествие по Самарканду и Ташкенту, Чимгану, Хиве, Янгиабад",
    from: "tashkent",
    languages: "english, russian, chinese",
    price: 600,
    forPerson: true,
    priceWithoutDiscount: 710,
  },
];
